pub enum SpecialText<'a> {
    Hero,
    Partner,
    Team,
    R,
    Icon(&'a str),
    Unknown,
}

impl From<&str> for SpecialText<'_> {
    fn from(item: &str) -> Self {
        match item {
            "hero" | "player" => SpecialText::Hero,
            "partner" => SpecialText::Partner,
            "team" | "team:" => SpecialText::Team,
            "R" => SpecialText::R,
            "M:BO" => SpecialText::Icon("Start"),
            "M:B1" => SpecialText::Icon("Select"),
            "M:B2" => SpecialText::Icon("A"),
            "M:B3" => SpecialText::Icon("B"),
            "M:B4" => SpecialText::Icon("X"),
            "M:B5" => SpecialText::Icon("Y"),
            "M:B6" => SpecialText::Icon("L"),
            "M:B7" => SpecialText::Icon("R"),
            "M:B8" => SpecialText::Icon("D-Pad"),
            "M:B9" => SpecialText::Icon("- Block"),
            "M:B10" => SpecialText::Icon("Check Block"),
            "M:B11" => SpecialText::Icon("X Block"),
            "M:B12" => SpecialText::Icon("Up Block"),
            "M:B13" => SpecialText::Icon("Down Block"),
            "M:B14" => SpecialText::Icon("Left Block"),
            "M:B15" => SpecialText::Icon("Right Block"),
            "M:B16" => SpecialText::Icon("Rewind Block"),
            "M:B17" => SpecialText::Icon("Forward Block"),
            "M:B18" => SpecialText::Icon("Sort Block"),
            "M:B19" => SpecialText::Icon("Search Block"),
            "M:B20" => SpecialText::Icon("D-Pad U-D Block"),
            "M:B21" => SpecialText::Icon("D-Pad L-R Block"),
            "M:B22" => SpecialText::Icon("- Gold Block"),
            "M:B23" => SpecialText::Icon("Check Gold Block"),
            "M:B24" => SpecialText::Icon("X Gold Block"),
            "M:B25" => SpecialText::Icon("Up Gold Block"),
            "M:B26" => SpecialText::Icon("Down Gold Block"),
            "M:B27" => SpecialText::Icon("Left Gold Block"),
            "M:B28" => SpecialText::Icon("Right Gold Block"),
            "M:B29" => SpecialText::Icon("Rewind Gold Block"),
            "M:B30" => SpecialText::Icon("FF Gold Block"),
            "M:B31" => SpecialText::Icon("Sort Gold Block"),
            "M:B32" => SpecialText::Icon("Search Gold Block"),
            "M:S0" => SpecialText::Icon("P-Money"),
            "M:S1" => SpecialText::Icon("Space"),
            "M:S2" => SpecialText::Icon("Check"),
            "M:S3" => SpecialText::Icon("Star"),
            "M:S4" => SpecialText::Icon("X"),
            "M:S5" => SpecialText::Icon("Check X"),
            "M:S6" => SpecialText::Icon("Bag"),
            "M:S7" => SpecialText::Icon("Hut"),
            "M:H0" => SpecialText::Icon("Heart Pink Tiny"),
            "M:H1" => SpecialText::Icon("Heart Pink Small"),
            "M:H2" => SpecialText::Icon("Heart Pink"),
            "M:H3" => SpecialText::Icon("Heart Pink Big"),
            "M:H4" => SpecialText::Icon("Heart Yellow Tiny"),
            "M:H5" => SpecialText::Icon("Heart Yellow Small"),
            "M:H6" => SpecialText::Icon("Heart Yellow"),
            "M:H7" => SpecialText::Icon("Heart Yellow Big"),
            "M:H8" => SpecialText::Icon("Heart Pink Unshaded"),
            "M:R0" => SpecialText::Icon("Dash"),
            "M:R1" => SpecialText::Icon("Half Star"),
            "M:R2" => SpecialText::Icon("Amber Gem?"),
            "M:R3" => SpecialText::Icon("Unopened Mail"),
            "M:R4" => SpecialText::Icon("Open Mail"),
            "M:R5" => SpecialText::Icon("Letter"),
            "M:R6" => SpecialText::Icon("Newspaper"),
            "M:R7" => SpecialText::Icon("! Box"),
            "M:R8" => SpecialText::Icon("Wi-Fi"),
            "M:R9" => SpecialText::Icon("E-Mail"),
            "M:T0" => SpecialText::Icon("Colon"),
            "M:T1" => SpecialText::Icon("Text Bubble"),
            "M:T2" => SpecialText::Icon("Space Indicator"),
            "M:T3" => SpecialText::Icon("Space Indicator Red"),
            "M:T4" => SpecialText::Icon("Kanji 1"),
            "M:T5" => SpecialText::Icon("Kanji 2"),
            "M:T6" => SpecialText::Icon("Kanji 3"),
            "M:I0" => SpecialText::Icon("TM"),
            "M:I1" => SpecialText::Icon("Orb"),
            _ => SpecialText::Unknown,
        }
    }
}
